---
# purpose: Create dummies interfaces abd bridges.
# CAUTION: WIll reboot the KVM server
# CAUTION: It would change your selinux, forwarding and iptables seetings
# CAUTION: Will disable NetworkManager and firewall
# Author: Mauricio Rojas / pinrojas.com
 
- hosts: localhost
  gather_facts: no
  remote_user: root
  roles:
    - _bridges
#    - _bridges-reset
  vars:
    hypervisor: 192.168.1.113
    public_if: enp0s20f1
    bridges:
      - { name: datacenter,
          dummy_if: dummy0 ,
          macaddr: "52:54:00:7e:27:d0" ,
          dummy_ip: 10.10.10.1 ,
          netmask: 255.255.255.0
        }
      - { name: wan,
          dummy_if: dummy1 ,
          macaddr: "52:54:00:7e:27:d1" ,
          dummy_ip: 10.250.250.1 ,
          netmask: 255.255.255.0
        }
      - { name: inet,
          dummy_if: dummy2 ,
          macaddr: "52:54:00:7e:27:d2" ,
          dummy_ip: 80.80.80.1 ,
          netmask: 255.255.255.0
        }
      - { name: branch1,
          dummy_if: dummy3 ,
          macaddr: "52:54:00:7e:27:d1" ,
          dummy_ip: 172.16.10.100 ,
          netmask: 255.255.255.0
        }
      - { name: branch2,
          dummy_if: dummy4 ,
          macaddr: "52:54:00:7e:27:d1" ,
          dummy_ip: 172.16.20.100 ,
          netmask: 255.255.255.0
        }
